[versions]
agp = "8.13.2"
androidPdfViewer = "3.2.0-beta.3"
checkout = "1.6.33"
circleimageview = "2.2.0"
imagepicker = "2.1"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lottie = "6.4.0"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
gson = "2.10.1"
materialCalendarview = "1.4.3"
mpandroidchart = "v3.1.0"
okhttp = "4.12.0"
retrofit = "2.9.0"
roundedimageview = "2.3.0"
sdp = "1.0.6"
signaturePad = "1.3.1"
slf4jNop = "2.0.7"
ssp = "1.0.6"
hilt = "2.52"
coroutines = "1.7.3"
lifecycle = "2.10.0"
glide = "4.15.1"
glide-compiler = "4.15.1"
javapoet = "1.13.0"

firebase-bom = "34.7.0"
crashlytics-gradle = "3.0.6"
google-services = "4.4.4"
navigationFragmentKtx = "2.9.6"
navigationUiKtx = "2.9.6"
playServicesLocation = "21.3.0"
firebaseDatabaseKtx = "21.0.0"
ucrop = "2.2.8"
workRuntimeKtx = "2.11.0"
hiltCommon = "1.3.0"
firebaseMessagingKtx = "24.1.2"
playServicesMaps = "19.2.0"
zxingAndroidEmbedded = "4.3.0"

[libraries]
android-pdf-viewer = { module = "com.github.mhiew:android-pdf-viewer", version.ref = "androidPdfViewer" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
checkout = { module = "com.razorpay:checkout", version.ref = "checkout" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagepicker" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-calendarview = { module = "com.prolificinteractive:material-calendarview", version.ref = "materialCalendarview" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
lifecycle-viewmodel-ktx = {module = "androidx.lifecycle:lifecycle-viewmodel-ktx",version.ref = "lifecycle"}
lifecycle-runtime-ktx = {module = "androidx.lifecycle:lifecycle-runtime-ktx",version.ref = "lifecycle"}
roundedimageview = { module = "com.makeramen:roundedimageview", version.ref = "roundedimageview" }
sdp = { module = "com.intuit.sdp:sdp-android", version.ref = "sdp" }
signature-pad = { module = "com.github.gcacace:signature-pad", version.ref = "signaturePad" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4jNop" }
ssp = { module = "com.intuit.ssp:ssp-android", version.ref = "ssp" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
lifecycleLiveDataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
#glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideCompiler" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version = "18.6.2" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version = "21.6.1" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }     # optional
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltCommon" }
hilt-work-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltCommon" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
google-maps-utils = { group = "com.google.maps.android", name = "android-maps-utils", version = "2.3.0" }
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }
#ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics-gradle" }


